name: MegaClassifier
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ruff
  - pip:
    - python-dotenv
    - -e .
    - tomlkit
    - gradio
    - supervision
    - commitizen
    - -r yolov5/requirements.txt
variables:
  PYTHONPATH: ./yolov5
